#!/bin/bash -e
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
[ -x $SCRIPTDIR/configure ] && source $SCRIPTDIR/configure

if [ -z "$BUILD_DEFINITIONS" ]; then 
    BUILD_DEFINITIONS="${1:-$HOME/dev/build-definitions}" 
fi
if [ -z "$EXPORT_DIR" ]; then 
    EXPORT_DIR="${2:-$HOME/dev/dance-standard-pipelines/pac}" 
fi

echo "Import Pipelines From $BUILD_DEFINITIONS" 
echo "Copy Pipelines Into $EXPORT_DIR" 

IMPORT_TASKS_DIR=${BUILD_DEFINITIONS}/task 
IMPORT_PIPELINES_DIR=${BUILD_DEFINITIONS}/pipelines
   
OUTPUT_TASKS_DIR=$EXPORT_DIR/tasks
OUTPUT_PIPELINES_DIR=$EXPORT_DIR/pipelines

rm -rf $OUTPUT_TASKS_DIR 
mkdir -p $OUTPUT_TASKS_DIR
rm -rf $OUTPUT_PIPELINES_DIR 
mkdir -p $OUTPUT_PIPELINES_DIR

for task in $(ls $IMPORT_TASKS_DIR); do
  VERSIONDIR=$(ls -d $IMPORT_TASKS_DIR/$task/*/ | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -n1)
  echo $task.yaml
  if [ -f $VERSIONDIR/$task.yaml ]; then
    cp $VERSIONDIR/$task.yaml $OUTPUT_TASKS_DIR/$task.yaml
  elif [ -f $VERSIONDIR/kustomization.yaml ]; then
    kustomize build $VERSIONDIR > $OUTPUT_TASKS_DIR/$task.yaml 
  else
    echo Unable to apply task in $VERSIONDIR
  fi
done

if [ -d $IMPORT_PIPELINES_DIR/dance ]; then
  echo "Using Dance from Build definitions"
  IMPORT_PIPELINES_DIR="$IMPORT_PIPELINES_DIR/dance" 
fi 

INDIVIDUAL_PIPELINES=$( yq .resources $IMPORT_PIPELINES_DIR/kustomization.yaml  | sed s/-// | xargs -n1 echo -n " ")

for pipe in $INDIVIDUAL_PIPELINES 
do
echo $pipe
PIPE_FILE_OR_DIR=$IMPORT_PIPELINES_DIR/$pipe
if [ -f $PIPE_FILE_OR_DIR ]; then
    cp $PIPE_FILE_OR_DIR $OUTPUT_PIPELINES_DIR/$pipe
  elif [ -f $PIPE_FILE_OR_DIR/kustomization.yaml ]; then
    OUT_FILE=$(basename $pipe)
    kustomize build $PIPE_FILE_OR_DIR | \
      yq e 'del(.items.[] | .spec.tasks.[] | .taskRef.version, .items.[] | .spec.finally.[] | .taskRef.version)' | \
      yq e 'del(.spec.tasks.[].taskRef.version)' | \
      yq e 'del(.spec.finally.[].taskRef.version)' | \
      cat  > $OUTPUT_PIPELINES_DIR/$OUT_FILE.yaml 
  else
    echo Unable to process pipeline in $IMPORT_PIPELINES_DIR/$pipe
  fi

done 

