apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{values.name}}-on-push
  namespace: {{values.namespace}}
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "{{values.rawUrl}}/pac/pipelines/docker-build-dance.yaml"
    pipelinesascode.tekton.dev/task-0: "{{values.rawUrl}}/pac/tasks/init.yaml"
    pipelinesascode.tekton.dev/task-1: "{{values.rawUrl}}/pac/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "{{values.rawUrl}}/pac/tasks/buildah.yaml"
    pipelinesascode.tekton.dev/task-3: "{{values.rawUrl}}/pac/tasks/source-build.yaml"
    pipelinesascode.tekton.dev/task-4: "{{values.rawUrl}}/pac/tasks/clair-scan.yaml"
    pipelinesascode.tekton.dev/task-5: "{{values.rawUrl}}/new-for-dance/tasks/task-acs-image-check.yaml"
    pipelinesascode.tekton.dev/task-6: "{{values.rawUrl}}/new-for-dance/tasks/task-acs-image-scan.yaml"
    pipelinesascode.tekton.dev/task-7: "{{values.rawUrl}}/new-for-dance/tasks/task-acs-deploy-check.yaml"
    pipelinesascode.tekton.dev/task-8: "{{values.rawUrl}}/pac/tasks/show-sbom.yaml"
    pipelinesascode.tekton.dev/task-9: "{{values.rawUrl}}/pac/tasks/summary.yaml"
spec: 
  params:
  - name: dockerfile
    value: {{values.dockerfileLocation}}
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: {{values.image}}:{{revision}}
  - name: path-context
    value: {{values.buildContext}}
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: docker-build-dance
  workspaces:
    - name: workspace
      volumeClaimTemplate: 
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi